# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: brick_test_development
  username: bishinho
  host: bishinho
  pool: 5
  port: 3000
  
